<a href="https://colab.research.google.com/github/bhagyapatel/Data-Scientest-/blob/main/Simplelinear2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
%matplotlib inline

In [4]:
from google.colab import files 
uploaded = files.upload()

Saving train.csv to train.csv


In [5]:
import pandas as pd 
import io

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['train.csv'])) 
print(df)

In [8]:
df.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [10]:
df_x = df.iloc[:,1:]
df_y = df.iloc[:,0]

In [11]:
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.2, random_state=4)

In [12]:
per = Perceptron()

In [13]:
per.fit(x_train,y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [14]:
pred = per.predict(x_test)

In [15]:
pred

array([0, 4, 0, ..., 0, 3, 1])

In [16]:
a = y_test.values
a

array([0, 4, 0, ..., 0, 3, 1])

In [17]:
count = 0
for i in range(len(pred)):
    if pred[i]==a[i]:
        count = count +1

In [18]:
count

7221

In [19]:
len(pred)

8400

In [20]:
7221/8400

0.8596428571428572

In [21]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes = (10,10,10), activation = 'relu', verbose = True, max_iter= 100)

In [22]:
mlp.fit(x_train, y_train)

Iteration 1, loss = 3.05451679
Iteration 2, loss = 1.94563128
Iteration 3, loss = 1.80850835
Iteration 4, loss = 1.65345981
Iteration 5, loss = 1.58012419
Iteration 6, loss = 1.54000503
Iteration 7, loss = 1.51545492
Iteration 8, loss = 1.45823819
Iteration 9, loss = 1.40137079
Iteration 10, loss = 1.34531174
Iteration 11, loss = 1.27654058
Iteration 12, loss = 1.16672365
Iteration 13, loss = 1.05590922
Iteration 14, loss = 0.99984720
Iteration 15, loss = 0.95391176
Iteration 16, loss = 0.91784333
Iteration 17, loss = 0.89002845
Iteration 18, loss = 0.85548476
Iteration 19, loss = 0.82794860
Iteration 20, loss = 0.79029000
Iteration 21, loss = 0.74533949
Iteration 22, loss = 0.71450787
Iteration 23, loss = 0.67413987
Iteration 24, loss = 0.62491936
Iteration 25, loss = 0.58549451
Iteration 26, loss = 0.55093387
Iteration 27, loss = 0.52640079
Iteration 28, loss = 0.51306803
Iteration 29, loss = 0.49616897
Iteration 30, loss = 0.48795123
Iteration 31, loss = 0.46313181
Iteration 32, los

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=100,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [23]:
preds_mlp = mlp.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [25]:
cm_mlp = confusion_matrix(y_test, preds_mlp)
acc_mlp = accuracy_score(y_test, preds_mlp)
print(cm_mlp)
print(acc_mlp)

[[790   0  11   0   3   3  23   1   2   1]
 [  1 875   9   2   2   2   0   5  10   1]
 [ 15   8 759  17   9   1  12   9  10   3]
 [  3   1  52 682   3  52   4   9  35  10]
 [  1   5   6   0 657   3  21   1   9  58]
 [ 18   7   9  52  11 569  36   1  41   9]
 [ 15   2  18   0   7   4 797   0  15   0]
 [  6   4  25  11   2   0   0 798   2  50]
 [  1  16  13  16  11  19  15   3 702   7]
 [  5   0   3   9  54  15   2  31  12 761]]
0.8797619047619047
